"""
constantes.py — Valores compartidos entre todos los módulos.
"""

# Colores por clasificación de obesidad
COLOR_CLASIFICACION = {
    "Sin obesidad":        "#2ecc71",   # verde
    "Obesidad preclínica": "#f39c12",   # naranja
    "Obesidad clínica":    "#e74c3c",   # rojo
}

# Lista de signos y síntomas (fuente: signosysintomas.sqlite)
TODOS_LOS_SIGNOS = [
    "Sin signos",
    "[Síntoma] Acantosis nigricans",
    "[Síntoma] Acantosis nigricans",
    "[Síntoma] Aislamiento social",
    "[Síntoma] Alteraciones del sueño",
    "[Síntoma] Ansiedad",
    "[Síntoma] Anuria",
    "[Síntoma] Apnea del sueño",
    "[Síntoma] Apnea obstructiva del sueño",
    "[Síntoma] Arritmia",
    "[Síntoma] Ascitis",
    "[Síntoma] Aumento de peso",
    "[Síntoma] Baja autoestima",
    "[Síntoma] Baja energía",
    "[Síntoma] Baja tolerancia al esfuerzo",
    "[Síntoma] Bajo rendimiento físico",
    "[Síntoma] Bradicardia",
    "[Síntoma] Calambres",
    "[Síntoma] Cardiopatía",
    "[Síntoma] Caídas frecuentes",
    "[Síntoma] Cefalea",
    "[Síntoma] Cianosis",
    "[Síntoma] Colesterol elevado",
    "[Síntoma] Confusión",
    "[Síntoma] Debilidad muscular",
    "[Síntoma] Dependencia física parcial",
    "[Síntoma] Depresión",
    "[Síntoma] Desmayo",
    "[Síntoma] Diabetes establecida",
    "[Síntoma] Diabetes mellitus tipo 2",
    "[Síntoma] Dificultad para caminar",
    "[Síntoma] Dificultad para concentrarse",
    "[Síntoma] Dificultad para perder peso",
    "[Síntoma] Dificultad para realizar actividades diarias",
    "[Síntoma] Discapacidad funcional",
    "[Síntoma] Disfunción eréctil",
    "[Síntoma] Dislipidemia",
    "[Síntoma] Disminución de libido",
    "[Síntoma] Disnea",
    "[Síntoma] Disnea de esfuerzo",
    "[Síntoma] Distensión abdominal",
    "[Síntoma] Dolor abdominal",
    "[Síntoma] Dolor articular",
    "[Síntoma] Dolor lumbar",
    "[Síntoma] Dolor muscular",
    "[Síntoma] Dolor torácico",
    "[Síntoma] Edema periférico",
    "[Síntoma] Edema pulmonar",
    "[Síntoma] Enfermedad cardiovascular",
    "[Síntoma] Enfermedad coronaria",
    "[Síntoma] Entumecimiento",
    "[Síntoma] Eritema",
    "[Síntoma] Eructos frecuentes",
    "[Síntoma] Esteatosis hepática",
    "[Síntoma] Estreñimiento",
    "[Síntoma] Estrés",
    "[Síntoma] Estrías",
    "[Síntoma] Fatiga",
    "[Síntoma] Fatiga cardiovascular",
    "[Síntoma] Fatiga crónica",
    "[Síntoma] Fatiga emocional",
    "[Síntoma] Fatiga muscular",
    "[Síntoma] Fatiga postprandial",
    "[Síntoma] Fatiga respiratoria",
    "[Síntoma] Flatulencia",
    "[Síntoma] Frecuencia urinaria aumentada",
    "[Síntoma] Hambre nocturna",
    "[Síntoma] Hematuria",
    "[Síntoma] Hepatomegalia",
    "[Síntoma] Hiperglucemia",
    "[Síntoma] Hipertensión arterial",
    "[Síntoma] Hipertensión persistente",
    "[Síntoma] Hipertrigliceridemia",
    "[Síntoma] Hipoglucemia",
    "[Síntoma] Hipogonadismo",
    "[Síntoma] Hipoventilación",
    "[Síntoma] Hormigueo",
    "[Síntoma] Hígado graso",
    "[Síntoma] Hígado graso avanzado",
    "[Síntoma] Ictericia",
    "[Síntoma] Incontinencia urinaria",
    "[Síntoma] Infarto agudo de miocardio",
    "[Síntoma] Infecciones cutáneas recurrentes",
    "[Síntoma] Infertilidad",
    "[Síntoma] Inflamación articular",
    "[Síntoma] Ingurgitación yugular",
    "[Síntoma] Insomnio",
    "[Síntoma] Insuficiencia cardíaca",
    "[Síntoma] Insuficiencia respiratoria",
    "[Síntoma] Intolerancia al ejercicio",
    "[Síntoma] Intolerancia al ejercicio",
    "[Síntoma] Intolerancia al esfuerzo",
    "[Síntoma] Irregularidades menstruales",
    "[Síntoma] Irritabilidad",
    "[Síntoma] Irritación cutánea",
    "[Síntoma] Limitación funcional",
    "[Síntoma] Limitación funcional",
    "[Síntoma] Limitación severa de movilidad",
    "[Síntoma] Mareo",
    "[Síntoma] Migraña",
    "[Síntoma] Nefropatía",
    "[Síntoma] Neuropatía periférica",
    "[Síntoma] Nocturia",
    "[Síntoma] Náuseas",
    "[Síntoma] Oliguria",
    "[Síntoma] Opresión en el pecho",
    "[Síntoma] Orina oscura",
    "[Síntoma] Ortopnea",
    "[Síntoma] Osteoartritis",
    "[Síntoma] Palpitaciones",
    "[Síntoma] Polidipsia",
    "[Síntoma] Polifagia",
    "[Síntoma] Poliuria",
    "[Síntoma] Prediabetes",
    "[Síntoma] Prurito",
    "[Síntoma] Pérdida de fuerza",
    "[Síntoma] Pérdida de memoria",
    "[Síntoma] Reflujo gastroesofágico",
    "[Síntoma] Resistencia a la insulina",
    "[Síntoma] Rigidez matutina",
    "[Síntoma] Ronquidos",
    "[Síntoma] Sed excesiva",
    "[Síntoma] Sedentarismo progresivo",
    "[Síntoma] Sensación de ahogo",
    "[Síntoma] Sibilancias",
    "[Síntoma] Somnolencia",
    "[Síntoma] Somnolencia diurna",
    "[Síntoma] Soplo cardíaco",
    "[Síntoma] Sudoración excesiva",
    "[Síntoma] Sudoración nocturna",
    "[Síntoma] Síndrome de ovario poliquístico",
    "[Síntoma] Síndrome metabólico",
    "[Síntoma] Taquicardia",
    "[Síntoma] Taquipnea",
    "[Síntoma] Tos nocturna",
    "[Síntoma] Visión borrosa",
    "[Síntoma] Xerosis",
]
