"""
constantes.py — Valores compartidos entre todos los módulos.
"""

# Colores por clasificación de obesidad
COLOR_CLASIFICACION = {
    "Sin obesidad":        "#2ecc71",   # verde
    "Obesidad preclínica": "#f39c12",   # naranja
    "Obesidad clínica":    "#e74c3c",   # rojo
}

# Lista de signos y síntomas (fuente: signosysintomas.sqlite)
TODOS_LOS_SIGNOS = [
    "Sin signos",
    "[Signo] Afasia",
    "[Síntoma] Afonía",
    "[Signo] Agitación",
    "[Signo] Alopecia",
    "[Signo] Anhidrosis",
    "[Signo] Anorexia",
    "[Síntoma] Ansiedad",
    "[Signo] Anuria",
    "[Signo] Apnea",
    "[Signo] Arritmia",
    "[Signo] Ascitis",
    "[Signo] Astenia",
    "[Signo] Ataxia",
    "[Síntoma] Aumento de peso",
    "[Síntoma] Aumento del apetito",
    "[Síntoma] Baja energía",
    "[Síntoma] Bajo rendimiento físico",
    "[Síntoma] Boca seca",
    "[Signo] Bradicardia",
    "[Signo] Bradipnea",
    "[Signo] Brillo ocular anormal",
    "[Síntoma] Calambres",
    "[Síntoma] Cambios del gusto",
    "[Síntoma] Cambios del olfato",
    "[Síntoma] Cansancio matutino",
    "[Síntoma] Caídas frecuentes",
    "[Signo] Cianosis",
    "[Signo] Cianosis central",
    "[Signo] Cianosis periférica",
    "[Signo] Coma",
    "[Síntoma] Confusión",
    "[Signo] Confusión mental",
    "[Síntoma] Congestión nasal",
    "[Signo] Convulsiones",
    "[Signo] Crepitantes",
    "[Síntoma] Debilidad",
    "[Signo] Deformidad articular",
    "[Síntoma] Depresión",
    "[Signo] Deshidratación",
    "[Síntoma] Desmayo",
    "[Signo] Desorientación",
    "[Síntoma] Desorientación",
    "[Signo] Diarrea",
    "[Síntoma] Diarrea",
    "[Síntoma] Dificultad para caminar",
    "[Síntoma] Dificultad para concentrarse",
    "[Síntoma] Dificultad para hablar",
    "[Síntoma] Dificultad para respirar",
    "[Signo] Disartria",
    "[Síntoma] Disfagia",
    "[Síntoma] Disfonía",
    "[Síntoma] Disminución de orina",
    "[Signo] Disnea",
    "[Signo] Distensión abdominal",
    "[Síntoma] Distensión abdominal",
    "[Signo] Disuria",
    "[Signo] Dolor abdominal",
    "[Síntoma] Dolor abdominal",
    "[Síntoma] Dolor al orinar",
    "[Síntoma] Dolor articular",
    "[Síntoma] Dolor cervical",
    "[Síntoma] Dolor de cabeza",
    "[Síntoma] Dolor de garganta",
    "[Síntoma] Dolor en extremidades",
    "[Signo] Dolor generalizado",
    "[Síntoma] Dolor generalizado",
    "[Signo] Dolor localizado",
    "[Síntoma] Dolor lumbar",
    "[Síntoma] Dolor muscular",
    "[Síntoma] Dolor torácico",
    "[Signo] Edema",
    "[Signo] Edema periférico",
    "[Signo] Edema pulmonar",
    "[Síntoma] Enrojecimiento",
    "[Síntoma] Entumecimiento",
    "[Signo] Equimosis",
    "[Signo] Eritema",
    "[Síntoma] Eructos frecuentes",
    "[Síntoma] Erupciones cutáneas",
    "[Síntoma] Escalofríos",
    "[Signo] Espasmos",
    "[Signo] Esplenomegalia",
    "[Signo] Estreñimiento",
    "[Síntoma] Estreñimiento",
    "[Signo] Expectoración",
    "[Síntoma] Falta de equilibrio",
    "[Síntoma] Fatiga",
    "[Síntoma] Fatiga visual",
    "[Signo] Fiebre",
    "[Síntoma] Fiebre subjetiva",
    "[Síntoma] Flatulencia",
    "[Signo] Fotofobia",
    "[Síntoma] Fotofobia",
    "[Síntoma] Frecuencia urinaria aumentada",
    "[Síntoma] Hambre nocturna",
    "[Signo] Hematoquecia",
    "[Signo] Hematuria",
    "[Signo] Hemiparesia",
    "[Signo] Hemoptisis",
    "[Signo] Hemorragia",
    "[Signo] Hepatomegalia",
    "[Signo] Hiperestesia",
    "[Signo] Hiperglucemia",
    "[Signo] Hiperreflexia",
    "[Signo] Hipertensión",
    "[Signo] Hipertonía",
    "[Síntoma] Hipo",
    "[Signo] Hipoestesia",
    "[Signo] Hipoglucemia",
    "[Signo] Hiporreflexia",
    "[Signo] Hipotensión",
    "[Signo] Hipotonía",
    "[Síntoma] Hormigueo",
    "[Signo] Ictericia",
    "[Signo] Incontinencia urinaria",
    "[Síntoma] Incontinencia urinaria",
    "[Signo] Inflamación",
    "[Signo] Ingurgitación yugular",
    "[Síntoma] Insomnio",
    "[Síntoma] Intolerancia al calor",
    "[Síntoma] Intolerancia al frío",
    "[Síntoma] Irritabilidad",
    "[Signo] Letargia",
    "[Signo] Linfadenopatía",
    "[Síntoma] Llanto frecuente",
    "[Síntoma] Mareo",
    "[Signo] Melena",
    "[Signo] Midriasis",
    "[Síntoma] Migraña",
    "[Signo] Miosis",
    "[Síntoma] Moretones",
    "[Síntoma] Nerviosismo",
    "[Signo] Nocturia",
    "[Signo] Náuseas",
    "[Síntoma] Náuseas",
    "[Síntoma] Ojos llorosos",
    "[Síntoma] Ojos secos",
    "[Signo] Oliguria",
    "[Síntoma] Opresión en pecho",
    "[Síntoma] Orina oscura",
    "[Signo] Ortopnea",
    "[Signo] Osteoporosis visible",
    "[Signo] Palidez",
    "[Síntoma] Palidez",
    "[Síntoma] Palpitaciones",
    "[Signo] Parestesia",
    "[Síntoma] Parestesia",
    "[Signo] Parálisis",
    "[Signo] Petequias",
    "[Síntoma] Picazón en piel",
    "[Síntoma] Piel fría",
    "[Signo] Polidipsia",
    "[Signo] Polifagia",
    "[Signo] Poliuria",
    "[Signo] Prurito",
    "[Síntoma] Pérdida de apetito",
    "[Síntoma] Pérdida de audición",
    "[Síntoma] Pérdida de memoria",
    "[Síntoma] Pérdida de peso",
    "[Signo] Rigidez abdominal",
    "[Síntoma] Rigidez matutina",
    "[Signo] Rigidez muscular",
    "[Síntoma] Ronchas",
    "[Signo] Roncus",
    "[Síntoma] Sabor metálico",
    "[Síntoma] Sangre en heces",
    "[Síntoma] Secreción nasal",
    "[Síntoma] Sed excesiva",
    "[Síntoma] Sensación de ahogo",
    "[Síntoma] Sensación de desmayo",
    "[Síntoma] Sensación de enfermedad",
    "[Síntoma] Sensación de vacío gástrico",
    "[Síntoma] Sensibilidad aumentada al dolor",
    "[Síntoma] Sequedad de piel",
    "[Signo] Sibilancias",
    "[Signo] Somnolencia",
    "[Síntoma] Somnolencia",
    "[Signo] Soplo cardíaco",
    "[Signo] Sudoración excesiva",
    "[Síntoma] Sudoración nocturna",
    "[Signo] Taquicardia",
    "[Signo] Taquipnea",
    "[Signo] Temblor",
    "[Síntoma] Temblor",
    "[Signo] Tos",
    "[Síntoma] Tos productiva",
    "[Síntoma] Tos seca",
    "[Síntoma] Urgencia urinaria",
    "[Signo] Urticaria",
    "[Síntoma] Visión borrosa",
    "[Signo] Vómito",
    "[Síntoma] Vómito",
    "[Signo] Xerosis",
    "[Síntoma] Zumbidos en oídos",
    ]
